
ARCHS?=i386 x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FRAMEWORKS=CoreFoundation Foundation CoreGraphics AVFoundation CoreVideo CoreMedia

FLAGS=-mmacosx-version-min=10.9 -D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC
LDFLAGS+=-mmacosx-version-min=10.9 -bundle -lstdc++ $(ARCHOPTS) \
    $(addprefix -framework ,$(FRAMEWORKS))

LD=clang++
CXX=clang++
